import { IS_MAC } from '../lib/format';
import { msg, useInterfaceLanguage } from '../i18n';
import { OriginalDesignationDialog } from './OriginalDesignationDialog';
import { AudioStorageIcon } from './AudioStorageIcon';
import { ProjectFileName } from './ProjectFileName';
import { ManuscriptImportHint } from './ManuscriptImportHint';
import { registerEditorDraft } from '../lib/editorDrafts';
import { PeopleInput } from './PeopleInput';
import { useEffect, useRef, useState, type DragEvent } from 'react';
import { AUDIO_EXT, createModel, defaultMetadata, readManifest, readModelEdit, readModelOriginal, renameModelLabel, setModelOriginal } from '../localStore';
import { recordingDirectory, mutateProjectManuscript, resolveMedia, type OpenProject, type ProjectInterview, type ProjectRecording } from '../lib/projectStore';
import { droppedFiles, reorder } from '../lib/projectSetup';
import type { TranscriptModel } from '../types';
import { DateTimeInput } from './DateTimeInput';
import { validDateTime } from '../lib/dateTime';
import { InlineEdit } from './InlineEdit';
import { ProjectIcon } from './ProjectIcon';
interface Props {
 project: OpenProject; selected: string | null; busy: boolean;
 select: (id: string)=>void; save: (interviews: ProjectInterview[])=>void;
 add: (id?: string)=>void; importDocuments: (id: string, files: FileSystemFileHandle[], kind?: 'audio' | 'manuscript', audioId?: string, referenceable?: boolean)=>Promise<void>; createSession: (session: ProjectInterview)=>Promise<void>; open: (recording: ProjectRecording, modelId?: string)=>void;
 run: (work:()=>Promise<void>)=>Promise<void>;
 remove?: (r: ProjectRecording, model?: TranscriptModel, hasDocuments?: boolean)=>void;
 detach?: (r: ProjectRecording, modelId: string)=>Promise<void>;
 legacy: (r: ProjectRecording)=>void; relink: (r: ProjectRecording)=>void; associate: (r: ProjectRecording, model: TranscriptModel, anchor: DOMRect)=>void;
}
export function ProjectBoard({project,selected,busy,select,save,importDocuments,createSession,open,run,associate,detach,remove,relink}:Props){
  useInterfaceLanguage();
 const runManuscript=(work:()=>Promise<void>)=>run(()=>mutateProjectManuscript(project,work));
 const original=(m:TranscriptModel)=>!!m.designatedOriginal || (m.sourceKind!=='import'&&!!m.original&&!m.edits.length);
 const [unavailable,setUnavailable]=useState<Set<string>>(new Set());
 const [adding,setAdding]=useState(false);
 const [draft,setDraft]=useState({title:'',date:'',location:'',people:[] as string[],notes:''});
 const [dateError,setDateError]=useState(false);
 useEffect(()=>registerEditorDraft(()=>adding),[adding]);
 const newSession=()=>{setDraft({title:'',date:'',location:'',people:[],notes:''});setDateError(false);setAdding(true);};
 const session=project.data.interviews.find(s=>s.id===selected);
 useEffect(()=>{let cancelled=false;void Promise.all((session?.recordings??[]).filter(r=>r.storage!=='none').map(async r=>{try{await(await resolveMedia(project,session!.id,r)).getFile();return null;}catch{return r.id;}})).then(ids=>{if(!cancelled)setUnavailable(new Set(ids.filter((id):id is string=>id!==null)));});return()=>{cancelled=true;};},[project,session]);
 const [models,setModels]=useState<Record<string,TranscriptModel[]>>({});
 const [readError,setReadError]=useState('');
 const [originalTarget,setOriginalTarget]=useState<{recording:ProjectRecording;model:TranscriptModel}|null>(null);
 const [originalError,setOriginalError]=useState('');
 const [renaming,setRenaming]=useState<string|null>(null);
 const drag=useRef<{id:string;group:string}|null>(null);
 const [edge,setEdge]=useState<{id:string;after:boolean}|null>(null);
 useEffect(()=>{let cancelled=false;if(session)void Promise.all(session.recordings.map(async r=>[r.id,(await readManifest(await recordingDirectory(project,session.id,r),r.file))?.models??[]] as const)).then(entries=>{if(!cancelled){setModels(Object.fromEntries(entries));setReadError('');}}).catch(e=>{if(!cancelled)setReadError(e instanceof Error?e.message:msg('ProjectBoard.m0656'));});return()=>{cancelled=true;};},[project,session]);
 const [audioDocumentDrag,setAudioDocumentDrag]=useState<string|null>(null);
 const [documentDrag,setDocumentDrag]=useState(false);
 const chooseDocuments=(kind: 'audio' | 'manuscript' = 'manuscript', audioId?: string)=>{if(!session||busy)return;void run(async()=>{
   const picker=window as unknown as {showOpenFilePicker:(options:unknown)=>Promise<FileSystemFileHandle[]>};
   const files=await picker.showOpenFilePicker({multiple:true,types:[{description:msg('ProjectBoard.m0657'),accept:kind==='audio'?{'audio/*':AUDIO_EXT.map(ext=>`.${ext}`)}:{'text/plain':['.txt','.srt','.vtt'],'application/json':['.json'],'application/msword':['.doc'],'application/vnd.openxmlformats-officedocument.wordprocessingml.document':['.docx']}}]});
   if(files.length)await importDocuments(session.id,files,kind,audioId);
 });};
 const patch=(id:string,changes:Partial<ProjectInterview>)=>save(project.data.interviews.map(s=>s.id===id?{...s,...changes}:s));
 const patchRecording=(id:string,changes:Partial<ProjectRecording>)=>{if(session)patch(session.id,{recordings:session.recordings.map(r=>r.id===id?{...r,...changes}:r)});};
 const renameSession=(id:string,title:string)=>{if(title.trim())patch(id,{title:title.trim()});};
 function move(id:string,target:string,after:boolean,group:string){if(group==='sessions')save(reorder(project.data.interviews,id,target,after));else if(session){if(group==='audio'||group==='independent')patch(session.id,{recordings:reorder(session.recordings,id,target,after)});else{const list=orderedModels(group);patchRecording(group,{manuscriptOrder:reorder(list,id,target,after).map(m=>m.id)});}}setEdge(null);}
 function zone(id:string,group:string){return {'data-sort-edge':edge?.id===`${group}:${id}`?(edge.after?'after':'before'):undefined,onDragOver:(e:DragEvent<HTMLElement>)=>{if(!busy&&drag.current?.group===group){e.preventDefault();e.stopPropagation();const b=e.currentTarget.getBoundingClientRect();setEdge({id:`${group}:${id}`,after:e.clientY>b.top+b.height/2});}},onDrop:(e:DragEvent<HTMLElement>)=>{if(!busy&&drag.current?.group===group){e.preventDefault();e.stopPropagation();const b=e.currentTarget.getBoundingClientRect();move(drag.current.id,id,e.clientY>b.top+b.height/2,group);drag.current=null;}}};}
 function grip(id:string,group:string,label:string,peers:{id:string}[]){return <button className="setup-grip" type="button" disabled={busy} draggable={!busy} aria-label={msg('ProjectBoard.m0658', { v0: label })} data-tip={msg('extra.reorder', { key: IS_MAC ? '⌥↑ / ⌥↓' : 'Alt+↑ / Alt+↓' })} data-tip-pos="top" onDragStart={e=>{e.stopPropagation();drag.current={id,group};e.dataTransfer.setData('application/x-ripple-order',id);e.dataTransfer.effectAllowed='move';}} onDragEnd={()=>{drag.current=null;setEdge(null);}} onKeyDown={e=>{if(e.altKey&&['ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const at=peers.findIndex(i=>i.id===id),next=peers[at+(e.key==='ArrowUp'?-1:1)];if(next)move(id,next.id,e.key==='ArrowDown',group);}}}><ProjectIcon kind="grip"/></button>;}
 function orderedModels(recordingId:string){const list=models[recordingId]??[];const order=session?.recordings.find(r=>r.id===recordingId)?.manuscriptOrder??[];return [...list].sort((a,b)=>{const at=order.indexOf(a.id),bt=order.indexOf(b.id);return(at<0?order.length:at)-(bt<0?order.length:bt);});}
 const copyDocument=(r:ProjectRecording,m:TranscriptModel)=>void runManuscript(async()=>{
   if(!session)return;
   const dir=await recordingDirectory(project,session.id,r);
   const source=!original(m)&&m.edits.length?await readModelEdit(dir,r.file,m.id,m.activeEditId||m.edits[0].id):await readModelOriginal(dir,r.file,m.id);
   if(!source)throw new Error(msg('ProjectBoard.m0660'));
   const base=`${m.label||m.sourceName||m.engine} 副本`;
   const names=new Set((models[r.id]??[]).map(item=>item.label));
   let label=base;for(let n=2;names.has(label);n++)label=`${base} ${n}`;
   const result=await createModel(dir,r.file,{engine:m.engine,sourceKind:m.sourceKind,sourceName:m.sourceName,transcript:source.transcript,metadata:'metadata' in source ? (source as import('../localStore').EditedFile).metadata : session.metadata,label,setActive:false});
   const manifest=result.manifest;
   setModels(old=>({...old,[r.id]:manifest.models}));setRenaming(`${r.id}:${result.model.id}`);
 });
 const designate=(r:ProjectRecording,m:TranscriptModel,value:boolean)=>void runManuscript(async()=>{
   if(!session)return;
   try {
     const manifest=await setModelOriginal(await recordingDirectory(project,session.id,r),r.file,m.id,value);
     setModels(old=>({...old,[r.id]:manifest.models}));setOriginalTarget(null);
   } catch(error) {setOriginalError(error instanceof Error?error.message:msg('ProjectBoard.m0662'));}
 });
 const fileName=(id:string,name:string,label:string,onOpen:()=>void,onRename:(value:string)=>void)=><ProjectFileName name={name} label={label} editing={renaming===id} disabled={busy} onOpen={onOpen} onRename={onRename} onFinish={()=>setRenaming(null)}/>;
 const renameButton=(id:string,name:string)=><button type="button" className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0663', { v0: name })} data-tip={msg('ProjectBoard.m0664')} data-tip-pos="top" onClick={()=>setRenaming(id)}><ProjectIcon kind="rename"/></button>;
 const doc=(r:ProjectRecording,m:TranscriptModel,independent=false)=><div key={m.id} className="setup-document" {...zone(independent&&orderedModels(r.id).length===1?r.id:m.id,independent&&orderedModels(r.id).length===1?'independent':r.id)}><ProjectIcon kind="document"/><span className="setup-document-name">{fileName(`${r.id}:${m.id}`,m.label||m.sourceName||m.engine,msg('ProjectBoard.m0665'),()=>open(r,m.id),value=>{void runManuscript(async()=>{const manifest=await renameModelLabel(await recordingDirectory(project,session!.id,r),r.file,m.id,value);setModels(old=>({...old,[r.id]:manifest.models}));});})}{original(m)&&<span className="manuscript-original-badge" title={msg('ProjectBoard.m0666')}>{msg('ProjectBoard.m0667')}</span>}</span><span className="setup-row-actions">{renameButton(`${r.id}:${m.id}`,m.label||m.sourceName||m.engine)}{m.sourceKind==='import'&&<button type="button" className="material-remove" disabled={busy} aria-label={`${m.designatedOriginal?msg('ProjectBoard.m0668'):msg('ProjectBoard.m0669')} ${m.label||m.sourceName||m.engine}`} data-tip={m.designatedOriginal?msg('ProjectBoard.m0670'):msg('ProjectBoard.m0671')} data-tip-pos="top" aria-pressed={!!m.designatedOriginal} onClick={()=>{setOriginalError('');if(m.designatedOriginal)designate(r,m,false);else setOriginalTarget({recording:r,model:m});}}><ProjectIcon kind="original"/></button>}<button type="button" className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0672', { v0: m.label||m.sourceName||m.engine })} data-tip={msg('ProjectBoard.m0673')} data-tip-pos="top" onClick={()=>copyDocument(r,m)}><ProjectIcon kind="copy"/></button>{!independent&&detach&&<button type="button" className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0674', { v0: m.label||m.sourceName||m.engine })} data-tip={msg('ProjectBoard.m0675')} data-tip-pos="top" onClick={()=>void run(()=>detach(r,m.id))}><ProjectIcon kind="unlink"/></button>}{independent&&<button className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0676', { v0: m.label||m.sourceName||m.engine })} data-tip={msg('ProjectBoard.m0677')} data-tip-pos="top" onClick={e=>associate(r,m,e.currentTarget.getBoundingClientRect())}><svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.7" aria-hidden="true"><path d="m10 13 4-4M8 16l-1 1a4 4 0 0 1-6-6l5-5a4 4 0 0 1 6 0M16 8l1-1a4 4 0 0 1 6 6l-5 5a4 4 0 0 1-6 0"/></svg></button>}{remove&&<button className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0678', { v0: m.label||m.sourceName||m.engine })} data-tip={msg('ProjectBoard.m0679')} data-tip-pos="top" onClick={()=>remove(r,m)}><ProjectIcon kind="trash"/></button>}{independent&&orderedModels(r.id).length===1?grip(r.id,'independent',m.label||r.name,session!.recordings.filter(r=>r.storage==='none')):grip(m.id,r.id,m.label||m.sourceName||m.engine,orderedModels(r.id))}</span></div>;
 return <><div className="setup-body"><aside className="setup-sidebar" aria-label={msg('ProjectBoard.m0680')}><p className="section-label">{msg('ProjectBoard.m0681')}</p>{project.data.interviews.map(s=><div className={`setup-session${!adding&&selected===s.id?' is-selected':''}`} key={s.id} {...zone(s.id,'sessions')}><div role="button" tabIndex={0} className="setup-session-select" aria-disabled={busy} aria-pressed={!adding&&selected===s.id} onKeyDown={e=>{if(e.target===e.currentTarget && (e.key==='Enter'||e.key===' ')&&!busy){e.preventDefault();setAdding(false);select(s.id);}}} onClick={()=>{if(!busy){setAdding(false);select(s.id);}}}><ProjectIcon kind="mic"/><span><InlineEdit doubleClick disabled={busy} value={s.title} ariaLabel={msg('ProjectBoard.m0682', { v0: s.title })} onCommit={v=>renameSession(s.id,v)}/><small>{s.metadata?.recorded_at?.slice(0,10)||msg('ProjectBoard.m0683', { v0: s.recordings.filter(r=>r.storage!=='none').length })}</small></span></div>{grip(s.id,'sessions',s.title,project.data.interviews)}</div>)}<button className="setup-drop setup-new" disabled={busy} onClick={newSession}><ProjectIcon kind="plus"/>{msg('ProjectBoard.m0684')}</button></aside>
 <div className="setup-canvas">{readError&&<p role="alert" className="form-error">{readError}</p>}{adding?<form className="setup-session-form" onSubmit={e=>{e.preventDefault();if(!draft.title.trim())return;if(!validDateTime(draft.date)){setDateError(true);return;}void run(async()=>{const id=crypto.randomUUID();await createSession({id,title:draft.title.trim(),metadata:{...defaultMetadata(draft.title.trim()),id,recorded_at:draft.date||null,location:draft.location,notes:draft.notes,participants:draft.people.map(name=>({name,role:''}))},recordings:[]});setAdding(false);});}}>
 <h2><InlineEdit doubleClick={Boolean(draft.title)} disabled={busy} value={draft.title} ariaLabel={msg('ProjectBoard.m0685')} placeholder={msg('ProjectBoard.m0686')} onCommit={title=>setDraft(old=>({...old,title}))}/></h2>
 <div className="setup-fields"><div className="field setup-date-row"><span>{msg('ProjectBoard.m0687')}</span><DateTimeInput label={msg('ProjectBoard.m0688')} includeTime={false} autoFocus={false} value={draft.date} onChange={date=>{setDraft({...draft,date});setDateError(false);}} onCommit={()=>setDateError(!validDateTime(draft.date))} onCancel={()=>{setDraft({...draft,date:''});setDateError(false);}}/>{dateError&&<span role="alert" className="inline-date-error">{msg('ProjectBoard.m0689')}</span>}</div>
 <label className="field"><span>{msg('ProjectBoard.m0690')}</span><input disabled={busy} value={draft.location} onChange={e=>setDraft({...draft,location:e.target.value})}/></label>
 <div className="field"><span>{msg('ProjectBoard.m0691')}</span><PeopleInput disabled={busy} names={draft.people} onChange={people=>setDraft({...draft,people})}/></div>
 <label className="field"><span>{msg('ProjectBoard.m0692')}</span><input disabled={busy} value={draft.notes} onChange={e=>setDraft({...draft,notes:e.target.value})}/></label></div>
 <div className="project-actions setup-confirm-actions">{!draft.title.trim() && <small className="setup-next-hint">{msg('ProjectBoard.m0693')}</small>}<button type="button" className="cred-btn" disabled={busy} onClick={()=>setAdding(false)}>{msg('ProjectBoard.m0694')}</button><button className="cred-btn" disabled={busy||!draft.title.trim()}>{msg('ProjectBoard.m0695')}</button></div>
 </form>:session?<><h2><InlineEdit doubleClick disabled={busy} value={session.title} ariaLabel={msg('ProjectBoard.m0696')} onCommit={v=>renameSession(session.id,v)}/></h2><div className="setup-metadata">{(['recorded_at','location','participants'] as const).map(key=><span key={key}><ProjectIcon kind={key==='recorded_at'?'calendar':key==='location'?'location':'people'}/>{key==='participants'?<PeopleInput key={session.id} disabled={busy} names={session.metadata?.participants.map(p=>p.name)||[]} onChange={names=>patch(session.id,{metadata:{...(session.metadata??defaultMetadata(session.title)),participants:names.map(name=>session.metadata?.participants.find(p=>p.name===name)||{name,role:''})}})}/>:<InlineEdit doubleClick disabled={busy} value={key==='recorded_at'?session.metadata?.recorded_at?.slice(0,10)||'':session.metadata?.location||''} ariaLabel={key==='recorded_at'?msg('ProjectBoard.m0697'):key==='location'?msg('ProjectBoard.m0698'):msg('ProjectBoard.m0699')} inputType={key==='recorded_at'?'date':'text'} placeholder={key==='recorded_at'?msg('ProjectBoard.m0700'):key==='location'?msg('ProjectBoard.m0701'):msg('ProjectBoard.m0702')} onCommit={v=>patch(session.id,{metadata:{...(session.metadata??defaultMetadata(session.title)),[key]:key==='recorded_at'?v||null:v}})}/>}</span>)}</div><p className="setup-notes"><InlineEdit doubleClick disabled={busy} value={session.metadata?.notes||''} ariaLabel={msg('ProjectBoard.m0703')} placeholder={msg('ProjectBoard.m0704')} onCommit={notes=>patch(session.id,{metadata:{...(session.metadata??defaultMetadata(session.title)),notes}})}/></p>
 {session.recordings.filter(r=>r.storage!=='none').map(r=><article key={r.id} className="setup-audio" {...zone(r.id,'audio')}><div className="setup-audio-heading"><AudioStorageIcon storage={r.storage==='reference'?'reference':'copy'}/><div className="setup-audio-name"><strong>{fileName(r.id,r.name,msg('ProjectBoard.m0705'),()=>open(r),name=>patchRecording(r.id,{name}))}</strong></div><span className="setup-row-actions">{renameButton(r.id,r.name)}{(r.storage==='reference'||unavailable.has(r.id))&&<button type="button" className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0706', { v0: r.name })} data-tip={msg('ProjectBoard.m0707')} data-tip-pos="top" onClick={()=>relink(r)}><ProjectIcon kind="folder"/></button>}{remove&&<button className="material-remove" disabled={busy} aria-label={msg('ProjectBoard.m0708', { v0: r.name })} data-tip={msg('ProjectBoard.m0709')} data-tip-pos="top" onClick={()=>remove(r,undefined,orderedModels(r.id).length>0)}><ProjectIcon kind="trash"/></button>}{grip(r.id,'audio',r.name,session.recordings.filter(r=>r.storage!=='none'))}</span></div>
 {unavailable.has(r.id)&&<p className="settings-hint" role="status">{msg('ProjectBoard.m0710')}</p>}{orderedModels(r.id).length>0&&<div className="setup-linked">{orderedModels(r.id).map(m=>doc(r,m))}</div>}<button className={`setup-drop${audioDocumentDrag===r.id?' is-over':''}`} disabled={busy} aria-label={msg('ProjectBoard.m0711', { v0: r.name })} onClick={()=>chooseDocuments('manuscript',r.id)}
 onDragOver={e=>{if(!busy&&e.dataTransfer.types.includes('Files')){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='copy';setAudioDocumentDrag(r.id);}}}
 onDragLeave={()=>setAudioDocumentDrag(null)} onDrop={e=>{e.preventDefault();e.stopPropagation();setAudioDocumentDrag(null);if(busy||!e.dataTransfer.types.includes('Files'))return;const files=droppedFiles(e.dataTransfer);void run(async()=>{const selected=await files;if(selected.length)await importDocuments(session.id,selected.map(f=>f.handle),'manuscript',r.id);});}}><ProjectIcon kind="document"/>{msg('ProjectBoard.m0712')}</button><ManuscriptImportHint/></article>)}
 <button className="setup-drop setup-new" disabled={busy} onClick={()=>chooseDocuments('audio')} onDragOver={e=>{if(!busy&&e.dataTransfer.types.includes('Files')){e.preventDefault();e.dataTransfer.dropEffect='copy';}}} onDrop={e=>{e.preventDefault();if(busy||!e.dataTransfer.types.includes('Files'))return;const files=droppedFiles(e.dataTransfer);void run(async()=>{const selected=await files;if(selected.length)await importDocuments(session.id,selected.map(f=>f.handle),'audio',undefined,selected.every(f=>f.referenceable));});}}><ProjectIcon kind="audio"/>{msg('ProjectBoard.m0713')}</button>
 <section className="setup-independent"><h3>{msg('ProjectBoard.m0714')}</h3>{session.recordings.filter(r=>r.storage==='none').map(r=><div key={r.id} className="setup-independent-item" {...zone(r.id,'independent')}>{orderedModels(r.id).map(m=>doc(r,m,true))}{models[r.id]?.length===0&&<p className="settings-hint">{r.name}{msg('ProjectBoard.m0715')}</p>}</div>)}<button className={`setup-drop${documentDrag?' is-over':''}`} disabled={busy} onClick={()=>chooseDocuments()}
 onDragOver={e=>{if(!busy&&e.dataTransfer.types.includes('Files')){e.preventDefault();e.stopPropagation();e.dataTransfer.dropEffect='copy';setDocumentDrag(true);}}}
 onDragLeave={()=>setDocumentDrag(false)} onDrop={e=>{e.preventDefault();e.stopPropagation();setDocumentDrag(false);if(busy||!e.dataTransfer.types.includes('Files'))return;const files=droppedFiles(e.dataTransfer);void run(async()=>{const selected=await files;if(selected.length)await importDocuments(session.id,selected.map(f=>f.handle));});}}><ProjectIcon kind="document"/>{msg('ProjectBoard.m0716')}</button><ManuscriptImportHint/></section>
 </>:<p className="settings-hint">{msg('ProjectBoard.m0717')}</p>}</div></div>{originalTarget&&<OriginalDesignationDialog name={originalTarget.model.label||originalTarget.model.sourceName||originalTarget.model.engine} busy={busy} error={originalError} onCancel={()=>setOriginalTarget(null)} onConfirm={()=>designate(originalTarget.recording,originalTarget.model,true)}/>} {!originalTarget&&originalError&&<p role="alert" className="form-error">{originalError}</p>}</>;
}
